version: '3.7'

services:

    php-fpm:
        build:
            context: php-fpm
        container_name: zinio_best_route_generator_php-fpm
        working_dir: /var/www/data/BoundedContext/BestRouteGenerator
        volumes:
            - type: bind
              source: ../../../
              target: /var/www/data
        ports:
            - "9901:9901"

volumes:
    volume_zinio_best_route_generator_neo4j:
